[package]
name = "mole"
version = "0.1.0"
authors = ["Jianing Yang <jianingy.yang@gmail.com>"]

[dependencies]
env_logger = "0.3"
itertools = "0.4.18"
lazy_static = "0.1"
log = "0.3"
regex = "0.1"
serde = "0.8.8"
ansi_term = "0.9.0"
r2d2 = "0.7.0"
r2d2_sqlite = "0.1.0"

[dependencies.clap]
version = "2"
features = ["suggestions", "color"]

[dependencies.serde_json]
version = "0.8"
