[package]
name = "mole"
version = "0.1.0"
authors = ["Jianing Yang <jianingy.yang@gmail.com>"]

[dependencies]
env_logger = "0.3"
lazy_static = "0.1"
log = "0.3"
regex = "0.1"

[dependencies.clap]
version = "2"
features = ["suggestions", "color"]
